name: Releases

on:
  push:
    branches: 
      - main

jobs:

  build:
    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate .exe file
        run: npm i && npm run create
        shell: bash 

      - name: Download .exe file
        uses: actions/download-artifact@v2
        with:
          name: monitory_sftw.exe



    