# nome do workflow
name: release

# aciona em todos os commits tags começados com "v" (ex: "v0.1.4")
on: 
  push:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1