# nome do workflow
name: release

# aciona em todos os commits tags começados com "v" (ex: "v0.1.4")
on: 
  push:
    tags:
      - main
      # - 'v*'


jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      run: echo "Running"
      shell: bash
    # - uses: ncipollo/release-action@v1