# nome do workflow
name: release

# aciona em todos os commits tags começados com "v" (ex: "v0.1.4")
on: 
  push:
    tags:
      - main


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: echo "Running"
      shell: bash