# nome do workflow
name: release

# aciona em todos os commits tags começados com "v" (ex: "v0.1.4")
on: 
  push:
    - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "Running"
      shell: bash